<?php

namespace app\home\controller\pay;

use app\common\model\PayRecharge;
use app\common\model\MoneyLog;
use app\home\controller\Base;
use app\common\model\SysConfig;
use think\facade\Log;
use app\home\controller\service\GoodsService;

class Pay extends Base
{
    public function initialize()
    {
		$this->service = new GoodsService();
        parent::initialize(); // TODO: Change the autogenerated stub
    }


    //获取当前 用户的个人信息
    public function pay()
    {
		// 基础数据 验证
		$price = $this->request->post('price/d', 0);
		if ($price <= 0)  return show([],config('ToConfig.http_code.error'),'充值金额错误');
		
		//生成充值订单  写入用户充值记录
		$user = session('home_user');
		$save_order = $this->service->recharge_user($user, $price);
		if ($save_order['code'] == 0)  return show([],config('ToConfig.http_code.error'),$save_order['msg']);

		//支付 数据准备
		$SysConfig=new SysConfig();
		$pay_api_notify_address=$SysConfig->where('name','pay_address')->value('value');	// 支付地址
		$web_address=$SysConfig->where('name','h5_address')->value('value'); 	// 前端地址
		$payData= [
			'mch_order' => $save_order['order_no'],
			'mch_id' => 300101,
			'url_notify' => $pay_api_notify_address.'/home/pay/pay_back',
			'url_redirect' => $web_address.'/',
			'money' => (float)sprintf("%.2f",$price),
			'td_code' => 8001,
			'title' => '用户充值',
		];
		
		// 配置参数
		$url='http://45.32.81.15/payorder/add';
		$key = 'Bak8bYeAlASNmZcBIGMYuvN7N6hxvjRs';
		// 签名
		$payData['sign'] = verifySignApplet($payData,$key);
		// 请求支付
		$curl_res=curl_post($url,$payData);
// 		Log::write('发送信息：'.implode($payData),'notice');
		Log::write('支付信息：'.$curl_res,'notice');
		// 如果失败
		if(!$curl_res) return show([],config('ToConfig.http_code.error'),'Invalid payment link');
		// 支付成功
		$curls_res=json_decode($curl_res,true);
		if ($curls_res['success']==1){
		    return show($curls_res,1);
		}else{
		    return show([],config('ToConfig.http_code.error'),$curls_res['msg']);
		}
    }
	
	// 支付成功 回调 函数
    public function pay_back(){
        Log::write('支付回调已进入','notice');
        $data =$_POST;
        if ($data){
            //记录下日志
            Log::write('支付回调信息：'.json_encode($data),'notice');
            //检测订单
            if ($data['status']==1){
                if ($data['mch_order']){
                    $PayRecharge=new PayRecharge();
                    $find=$PayRecharge->where('order_no',$data['mch_order'])->where('status',0)->find();
                    if ($find){
                        $UserModel=new UserModel();
                        $user=$UserModel->where('id',$find['uid'])->find();
                        Db::name('common_user')->where('id',$find['uid'])->inc('money_balance',$find['money'])->update();
                        Db::name('common_user')->where('id',$find['uid'])->inc('money_total_recharge',$find['money'])->update();
                        //记录
                        MoneyLog::flowing(1,1,1,101,$user,$find['money'],$find['id'],'充值');
                        $post['status']=1;
                        $post['success_time']=date('Y-m-d H:i:s');
                        $post['admin_uid']= 1;
                        $PayRecharge->where('id',$find['id'])->where('status',0)->save($post);
                    }
                }
                echo "SUCCESS";
                exit;
            }else{
                echo "error";
                exit;
            }
        }
    }

// 类结束了
}