<?php


namespace app\admin\controller\log;


use app\admin\controller\Base;
use app\common\model\MoneyLog as models;

class MoneyLog extends Base
{
    protected $model;

    /**
     * 资金流动控制器
     */
    public function initialize()
    {
        $this->model = new models();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 列表
     */
    public function index()
    {

        //当前页
        $page = $this->request->post('page', 1);
        //每页显示数量
        $limit = $this->request->post('limit', 10);
        //查询搜索条件
        $post = array_filter($this->request->post());
        $map =[];
        isset($post['status'])&& $map[]= ['a.status','=',$post['status']];
        isset($post['uid']) && $map[]= ['uid','=',$post['uid']];
        isset($post['user_name'])&& $map[]= ['b.user_name', 'like', '%' . $post['user_name'] . '%'];
        $order = 'a.id desc';
        isset($post['create_time_sort'])&& $order='a.id '.$post['create_time_sort'];

        $list =$this->model->page_list($map,$limit,$page,$order);

//        $list =$this->model->alias('a')->where($map)->withJoin([
//            'user'	=>	['user_name']
//        ])->page($page, $limit)->paginate(['list_rows'=>$limit,'page'=>$page]);;

        return $this->success($list);
    }
}