<?php


namespace app\admin\controller\log;


use app\admin\controller\Base;


use app\common\model\PayCash as models;
use app\common\traites\PublicCrudTrait;
use app\validate\Status;
use think\exception\ValidateException;

class PayCash extends Base
{
    protected $model;
    use PublicCrudTrait;

    /**
     * 提现控制器
     */
    public function initialize()
    {
        $this->model = new models();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 列表
     */
    public function index()
    {
        //当前页
        $page = $this->request->post('page', 1);
        //每页显示数量
        $limit = $this->request->post('limit', 10);
        //查询搜索条件
        $post = $this->request->post();
        $map=[];
        isset($post['user_name']) && $map [] = ['b.user_name', 'like', '%' . $post['user_name'] . '%'];
        isset($post['status']) && $map [] = ['a.status', '=',intval($post['status'])];

        $list = $this->model->page_list($map,$limit, $page);
        return $this->success($list);
    }

    /**
     * 提现成功状态修改
     */
    public function status()
    {
        //过滤数据
        $postField = 'id,status,msg';
        $post = $this->request->only(explode(',', $postField), 'post', null);

        try {
            validate(Status::class)->scene('status')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }

        //if ($post['status'] >= 1) return $this->failed('只能修改为成功拒绝状态');
        //查询当前提现，状态是提现成功不能修改为拒绝
        $find = $this->model->find($post['id']);
        if ($find->status == 1) return $this->failed('提现成功不能在修改');
        $save= $this->model->setStatus($post);
        if ($save) return $this->success([]);
        return $this->failed('修改失败');
    }

}