<?php

namespace app\home\controller\login;

use app\BaseController;
use app\common\model\VideoDetail;
use app\common\traites\PublicCrudTrait;
use app\home\controller\service\GoodsService;
use think\facade\Db;
use think\facade\Request;

class NoVerification extends BaseController
{

    protected $model;
    protected $service;
    use PublicCrudTrait;

    /**
     * 获取商品
     */
    public function initialize()
    {
        $this->service = new GoodsService();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    //查询视频分类
    public function video_type_list()
    {
        $find = $this->service->video_model()->video_type_list();
        if (!$find)  return show([],config('ToConfig.http_code.error'),'没有该分类哦！');
        return show($find);
    }

    // 查看全部视频列表
    public function video_all_list()
    {
        //获取视频列表
        $list = $this->service->video_all_list();
        if (!$list)  return show([],config('ToConfig.http_code.error'),'视频列表为空！暂无视频');
        return show($list);
    }

    //获取配置文件
    public function get_config()
    {
        $name = $this->request->param('name','');
        return show(get_config($name));
    }


    //随机给视频列表，作为轮播视频 短视频
    public function video_random_list(){
        $type_id = $this->request->param('type_id/d',0);

        $map = [];
        if (!empty($type_id)){
            $map[] = ['type'=>$type_id];
        }

        $VideoDetailModel = new VideoDetail();
        //查询数据库有多少条数据
        $count = $VideoDetailModel->where($map)->whereLike('vod_play_url','%.mp4')->count();
        $p = $count/6;
        $page = $this->request->param('page/d',rand(0,intval($count/6)));
        $list = $VideoDetailModel->where($map)->field('*,vod_play_url as video_url,	vod_pic as thumb_url')
            ->whereLike('vod_play_url','%.mp4')
            ->page($page,6)
            ->paginate()
            ->each(function($item, $key){
                return VideoDetail::videoInfoAdditional($item);
            });
        return show($list);
    }

    //随机给视频列表，作为轮播视频 长视频
    public function video_mp_random_list(){
        $type_id = $this->request->param('type_id/d',0);

        $map = [];
        if (!empty($type_id)){
            $map[] = ['type'=>$type_id];
        }

        $VideoDetailModel = new VideoDetail();
        //查询数据库有多少条数据
        $count = $VideoDetailModel->where($map)->whereLike('vod_play_url','%.m3u8%')->count();

        $page = $this->request->param('page/d',rand(0,intval($count/6)));
        $list = $VideoDetailModel->where($map)
            ->field('*,vod_play_url as video_url,	vod_pic as thumb_url')
            ->whereLike('vod_play_url','%.m3u8%')
            ->page($page,6)
            ->paginate()
            ->each(function($item, $key){
                return VideoDetail::videoInfoAdditional($item);
            });
        return show($list);
    }

    //评论列表
    public function video_comment_list(){
        $videoId = $this->request->param('video_id/d',0);
        if ($videoId <=0){
            return show([], config('ToConfig.http_code.error'), '视频ID错误');
        }
        $page = Request::post('page/d', 1);			// 当前页
        $limit = Request::post('limit/d', 20);		// 每页显示数量

       $list =  Db::name('video_comment')->order('id asc')->where(['content_id'=>$videoId])->paginate(['list_rows' => $limit, 'page' => $page]);;
        return show($list);
    }
}