<?php

namespace app\home\controller\user;

use app\common\model\UserModel as models;
use app\common\traites\PublicCrudTrait;
use app\home\controller\Base;
use app\common\model\PayRecharge;
use app\common\model\OrderModel;
use app\common\model\MoneyLog;
use think\facade\Db;
use think\facade\Log;
use think\facade\Request;

class User extends Base
{
    protected $model;
    use PublicCrudTrait;

    /**
     * 个人中心
     */
    public function initialize()
    {
        //判断不存在时直接 return出去
        $this->model = new models();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    //获取当前 用户的个人信息
    public function index()
    {
		$home_user= session('home_user');
		if (empty($home_user)) return show([],config('ToConfig.http_code.error'),'用户信息不存在，请登录');
		return show($home_user);
    }

//    //获取配置文件
//    public function get_config()
//    {
//        $name = $this->request->param('name','');
//        return show(get_config($name));
//    }
	// 当前用户的充值列表
	public function get_charge_list()
	{
		//当前页
		$page = Request::post('page/d', 1);
		//每页显示数量
		$limit = Request::post('limit/d', 20);
		// 获取用户基础信息
		$home_user= session('home_user');
		if (empty($home_user)) return show([],config('ToConfig.http_code.error'),'用户信息不存在，请登录');
		$uid = $home_user['id'];
		$PayRecharge=new PayRecharge();
		$list = $PayRecharge
			->where('uid',$uid)
			->where('status','<>',-1)
			->paginate(['list_rows' => $limit, 'page' => $page])
			->toArray();
		if (!$list)  return show([],config('ToConfig.http_code.error'),'没有充值信息！');
		$changeStatsToString = [
			'1' => '充值完成',
			'-1' => '已删除',
			'0' => '待确认'
		];
		foreach($list['data'] as $k => $v){
			$list['data'][$k]['status_text'] = $changeStatsToString[$v['status']];
		}
		return show($list);
	}
	 
	public function get_buyset_list()
	{
		//当前页
		$page = Request::post('page/d', 1);
		//每页显示数量
		$limit = Request::post('limit/d', 20);
		// 获取用户基础信息
		$home_user= session('home_user');
		if (empty($home_user)) return show([],config('ToConfig.http_code.error'),'用户信息不存在，请登录');
		$uid = $home_user['id'];
		$Order=new OrderModel();
		$list = $Order
			->where('uid',$uid)
			->where('status','<>',-1)
			->paginate(['list_rows' => $limit, 'page' => $page]);
		if (!$list)  return show([],config('ToConfig.http_code.error'),'没有套餐信息！');
		return show($list);
	}

    //查询用户提现记录
    public function get_withdrawal_list(){
        //当前页
        $page = Request::post('page/d', 1);
        //每页显示数量
        $limit = Request::post('limit/d', 20);
        // 获取用户基础信息
        $home_user= session('home_user');
        if (empty($home_user)) return show([],config('ToConfig.http_code.error'),'用户信息不存在，请登录');
        $uid = $home_user['id'];
        $MoneyLog=new MoneyLog();
        $list = $MoneyLog
            ->where('uid',$uid)
            ->where(['status'=>201])
            ->paginate(['list_rows' => $limit, 'page' => $page]);
        return show($list);
    }

    //修改昵称
    public function user_edit(){
        $nickname = Request::post('nickname', '');

        $image = Request::post('image', '');
        $update = [];
        if (empty($nickname) && empty($image)){
            return show();
        }

        !empty($nickname)  && $update['nickname'] = $nickname;
        !empty($image)  && $update['head_img'] = $image;

        $home_user= session('home_user');
        $this->model->where('id',$home_user['id'])->update($update);
        return show();
    }
}